/*File of Assertions for Testing*/

#include<assert.h>

#define TESTS_EQUAL_INT(EXPECTED, PRODUCED) assert(EXPECTED == PRODUCED);
#define TESTS_EQUAL_CHAR(EXPECTED, PRODUCED) assert(EXPECTED == PRODUCED);
#define TESTS_NOT_EQUAL(TEST, PRODUCED) assert(TEST != PRODUCED);
#define TESTS_EQUAL_FLOAT(EXPECTED, PRODUCED) assert(PRODUCED <= EXPECTED+.05 && PRODUCED >= EXPECTED-.05);
#define TESTS_EQUAL_STRING(EXPECTED, PRODUCED) assert(strcmp(EXPECTED, PRODUCED) == 0);
#define TESTS_IS_NULL(PRODUCED) assert(PRODUCED == NULL);
#define TESTS_NOT_NULL(PRODUCED) assert(PRODUCED != NULL);
#define TESTS_EQUAL_BOOLEAN(EXPECTED, PRODUCED) assert(EXPECTED == PRODUCED);
